name: SnapMyWindows
options:
  bundleIdPrefix: net.zachsai
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "13.0"

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 1.9.0

targets:
  SnapMyWindows:
    type: application
    platform: macOS
    sources:
      - path: SnapMyWindows
    dependencies:
      - package: KeyboardShortcuts
    entitlements:
      path: SnapMyWindows/SnapMyWindows.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true
    settings:
      ENABLE_APP_SANDBOX: YES
      CODE_SIGN_ENTITLEMENTS: SnapMyWindows/SnapMyWindows.entitlements
      DEVELOPMENT_TEAM: MHYWV59S73
    info:
      path: SnapMyWindows/Info.plist
      properties:
        LSUIElement: true
        CFBundleVersion: 1
        CFBundleShortVersionString: "1.0.0"
        NSAccessibilityUsageDescription: "Snap My Windows needs accessibility access to move and resize windows."

  SnapMyWindowsTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SnapMyWindowsTests
    dependencies:
      - target: SnapMyWindows
    settings:
      GENERATE_INFOPLIST_FILE: YES
